# global config
some:
  property: global
  other:
    property: global

management:
  endpoints:
    web:
      exposure:
        include: refresh

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8500/eureka/
  instance:
    preferIpAddress: true
